name: Spring Heroku Deploy

on:
  push:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate application.properties
      run: |
        cd src/main/resources
        echo "$APPLICATION_PROPERTIES" > application-prod.properties
        cd ../../../
      env:
        APPLICATION_PROPERTIES: "${{ secrets.APPLICATION_PROPERTIES }}"
        APPLICATION_PROPERTIES_B64: "${{ secrets.APPLICATION_PROPERTIES_B64 }}"
    - name: Generate Procfile
      run: |
        echo "$HEROKU_PROCFILE_B64" > Procfile.b64
        base64 -d -i Procfile.b64 > Procfile
      env:
        HEROKU_PROCFILE_B64: "${{ secrets.HEROKU_PROCFILE_B64 }}"
    - name: Generate system.properties
      run: |
        echo "$SYSTEM_PROPERTIES_B64" > system.properties.b64
        base64 -d -i system.properties.b64 > system.properties
        ls -lrta
      env:
        SYSTEM_PROPERTIES_B64: "${{ secrets.SYSTEM_PROPERTIES_B64 }}"
    - name: Generate firebase config
      run: |
        echo "$FIREBASE_CONFIG" > firebaseService.json
      env:
        FIREBASE_CONFIG: "${{ secrets.FIREBASE_CONFIG }}"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Deploy To Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}


        
        
   
        
