name: Spring Heroku Deploy

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Generate application.properties
      env:
        APPLICATION_PROPERTIES_B64: "${{ secrets.APPLICATION_PROPERTIES_B64 }}"
      run: |
        mkdir -p src/main/resources
        echo "$APPLICATION_PROPERTIES_B64" > src/main/resources/application.properties.b64
        base64 -d -i src/main/resources/application.properties.b64 > src/main/resources/application.properties
    - name: Generate Procfile
      env:
        HEROKU_PROCFILE_B64: "${{ secrets.HEROKU_PROCFILE_B64 }}"
      run: |
        echo "$HEROKU_PROCFILE_B64" > Procfile.b64
        base64 -d -i Procfile.b64 > Procfile
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    - name: Deploy Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
        
        
   
        
